import eslint from '@eslint/js';
import stylistic from '@stylistic/eslint-plugin';
import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';
import importPlugin from 'eslint-plugin-import';
import reactPlugin from 'eslint-plugin-react';
import tseslint from 'typescript-eslint';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  eslint.configs.recommended,
  tseslint.configs.strictTypeChecked,
  tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        projectService: true,
      },
    },
    plugins: {
      'react': reactPlugin,
      '@stylistic': stylistic,
      'import': importPlugin,
    },
    settings: {
      // Needed for TS path + extension resolution
      'import/resolver': {
        typescript: {
          alwaysTryTypes: true,
        },
        node: {
          extensions: [ '.js', '.jsx', '.ts', '.tsx' ],
        },
      },
    },
    rules: {
      'array-callback-return': 'error',
      'block-scoped-var': 'error',
      'curly': 'error',
      'dot-location': [ 'error', 'property' ],
      'dot-notation': 'off',
      'eqeqeq': 'error',
      'guard-for-in': 'error',
      'no-constructor-return': 'error',
      'no-div-regex': 'error',
      'no-else-return': 'error',
      'no-empty-function': 'error',
      'no-eq-null': 'error',
      'no-eval': 'error',
      'no-extend-native': 'error',
      'no-extra-bind': 'error',
      'no-extra-label': 'error',
      'no-floating-decimal': 'error',
      'no-implied-eval': 'off',
      'no-invalid-this': 'error',
      'no-iterator': 'error',
      'no-labels': 'error',
      'no-lone-blocks': 'error',
      'no-loop-func': 'off',
      'no-magic-numbers': 'off',
      'no-multi-spaces': 'error',
      'no-restricted-globals': 'error',
      'no-return-assign': 'error',
      'no-return-await': 'off',
      'no-script-url': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-throw-literal': 'off',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'error',
      'no-useless-call': 'error',
      'no-useless-concat': 'error',
      'no-useless-return': 'error',
      'no-void': 'off',
      'no-warning-comments': 'warn',
      'prefer-promise-reject-errors': 'error',
      'prefer-regex-literals': 'error',
      'radix': 'error',
      'require-await': 'off',
      'require-unicode-regexp': 'error',
      'wrap-iife': 'error',
      'yoda': 'error',
      'no-shadow': 'off',
      'no-unused-vars': 'off',
      'array-bracket-newline': [ 'error', 'consistent' ],
      'array-bracket-spacing': [ 'error', 'always' ],
      'array-element-newline': [ 'error', 'consistent' ],
      'block-spacing': 'error',
      'brace-style': 'off',
      'camelcase': 'error',
      'comma-dangle': 'off',
      'comma-spacing': 'off',
      'comma-style': 'error',
      'computed-property-spacing': 'error',
      'eol-last': 'error',
      'func-call-spacing': 'off',
      'function-call-argument-newline': [ 'error', 'consistent' ],
      'function-paren-newline': [ 'error', 'multiline-arguments' ],
      'implicit-arrow-linebreak': 'error',
      'indent': 'off',
      'jsx-quotes': 'error',
      'key-spacing': 'error',
      'keyword-spacing': 'off',
      'linebreak-style': [ 'error' ],
      'lines-between-class-members': 'off',
      'new-parens': 'error',
      'no-bitwise': 'error',
      'no-lonely-if': 'off',
      'no-mixed-operators': 'error',
      'no-multi-assign': 'error',
      'no-multiple-empty-lines': [ 'error', { max: 1, maxEOF: 0, maxBOF: 0 } ],
      'no-tabs': 'error',
      'no-trailing-spaces': 'error',
      'no-unneeded-ternary': 'error',
      'no-whitespace-before-property': 'error',
      'object-curly-newline': 'error',
      'object-curly-spacing': 'off',
      'object-property-newline': [ 'error', { allowAllPropertiesOnSameLine: true } ],
      'object-shorthand': 'error',
      'one-var': [ 'error', 'never' ],
      'padding-line-between-statements': [ 'error', {
        blankLine: 'always',
        prev: '*',
        next: 'function',
      } ],
      'quote-props': [ 'error', 'consistent-as-needed' ],
      'quotes': 'off',
      'semi': 'off',
      'semi-spacing': 'error',
      'semi-style': 'error',
      'space-before-blocks': 'error',
      'space-before-function-paren': 'off',
      'space-in-parens': 'error',
      'space-infix-ops': 'off',
      'space-unary-ops': 'error',
      'spaced-comment': 'error',
      'switch-colon-spacing': 'error',
      'template-tag-spacing': 'error',
      'arrow-parens': [ 'error', 'as-needed' ],
      'arrow-spacing': 'error',
      'generator-star-spacing': 'error',
      'no-confusing-arrow': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'sort-imports': [ 'error', {
        ignoreCase: true,
        ignoreDeclarationSort: true,
        ignoreMemberSort: false,
        memberSyntaxSortOrder: [ 'none', 'all', 'multiple', 'single' ],
        allowSeparatedGroups: true,
      } ],
      'template-curly-spacing': 'error',
      'yield-star-spacing': 'error',

      // @typescript-eslint rules
      '@typescript-eslint/consistent-type-imports': 'error',
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/explicit-member-accessibility': 'off',
      '@typescript-eslint/member-ordering': 'error',
      '@typescript-eslint/method-signature-style': 'error',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-confusing-void-expression': [ 'error', { ignoreArrowShorthand: true } ],
      '@typescript-eslint/no-var-requires': 'off',
      '@typescript-eslint/only-throw-error': 'error',
      '@typescript-eslint/prefer-for-of': 'error',
      '@typescript-eslint/prefer-includes': 'error',
      '@typescript-eslint/prefer-nullish-coalescing': 'error',
      '@typescript-eslint/prefer-optional-chain': 'error',
      '@typescript-eslint/prefer-readonly': 'error',
      '@typescript-eslint/promise-function-async': 'error',
      '@typescript-eslint/prefer-reduce-type-parameter': 'error',
      '@typescript-eslint/prefer-string-starts-ends-with': 'error',
      '@typescript-eslint/restrict-template-expressions': [ 'error', { allowNumber: true } ],

      // @typescript-eslint rules
      '@typescript-eslint/dot-notation': 'error',
      '@typescript-eslint/no-implied-eval': 'error',
      '@typescript-eslint/no-loop-func': 'error',
      '@typescript-eslint/no-magic-numbers': 'off',
      '@typescript-eslint/no-shadow': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-use-before-define': 'off',
      '@typescript-eslint/require-await': 'warn',
      '@typescript-eslint/return-await': 'error',

      // @stylistic rules
      '@stylistic/brace-style': [ 'error', '1tbs', {
        allowSingleLine: true,
      } ],
      '@stylistic/comma-dangle': [ 'error', 'always-multiline' ],
      '@stylistic/comma-spacing': 'error',
      '@stylistic/indent': [ 'error', 2 ],
      '@stylistic/function-call-spacing': 'error',
      '@stylistic/lines-between-class-members': [ 'error', 'always', {
        exceptAfterSingleLine: true,
      } ],
      '@stylistic/member-delimiter-style': 'error',
      '@stylistic/object-curly-spacing': [ 'error', 'always' ],
      '@stylistic/type-annotation-spacing': 'error',
      '@stylistic/quotes': [ 'error', 'single', {
        avoidEscape: true,
        allowTemplateLiterals: 'always',
      } ],
      '@stylistic/semi': 'error',
      '@stylistic/space-before-function-paren': [ 'error', {
        anonymous: 'always',
        named: 'never',
        asyncArrow: 'always',
      } ],
      '@stylistic/space-infix-ops': 'error',

      // react rules
      'react/jsx-closing-bracket-location': [ 'error', {
        location: 'line-aligned',
      } ],
      'react/jsx-curly-spacing': 'error',
      'react/jsx-equals-spacing': 'error',
      'react/jsx-first-prop-new-line': [ 'error', 'multiline' ],
      'react/jsx-fragments': 'error',
      'react/jsx-handler-names': [ 'error', {
        eventHandlerPrefix: 'handle',
        eventHandlerPropPrefix: 'on',
        checkLocalVariables: true,
        checkInlineFunction: true,
      } ],
      'react/jsx-indent': [ 'error', 2, {
        checkAttributes: true,
        indentLogicalExpressions: true,
      } ],
      'react/jsx-indent-props': [ 'error', 2 ],
      'react/jsx-pascal-case': [ 'error', {
        allowAllCaps: true,
        allowNamespace: true,
      } ],
      'react/jsx-props-no-multi-spaces': 'error',
      'react/jsx-tag-spacing': [ 'error', {
        beforeClosing: 'never',
      } ],
      'react/no-unescaped-entities': [ 'error', {
        forbid: [ '>', '"', '}', '“', '”', '‘', '’' ],
      } ],
      'react/no-unknown-property': [ 'error', {
        ignore: [ 'jsx' ],
      } ],
      'react/prop-types': 'off',
      'react/react-in-jsx-scope': 'off',
      'react/self-closing-comp': 'error',

      'import/order': [ 'error', {
        'alphabetize': {
          order: 'asc',
          orderImportKind: 'asc',
          caseInsensitive: true,
        },
        'groups': [
          [ 'builtin', 'external' ],
          [ 'internal', 'parent', 'sibling', 'index', 'object', 'unknown' ],
        ],
        'newlines-between': 'always',
      } ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // custom
    'public',
  ]),
  {
    ignores: [ 'node_modules/**', '.next/**', 'out/**', 'build/**', 'public/**', 'next-env.d.ts' ],
  },
]);

export default eslintConfig;
