const courses = [{
  code: 'FD',
  name: 'Floral Design',
  primary: true,
  cost: 1498,
  multiCourseDiscountRate: 0.5,
  multiCourseDiscount: 0,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 1498,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
},
{
  code: 'CP',
  name: 'Corporate Event Planning',
  primary: false,
  cost: 1384,
  multiCourseDiscountRate: 0.5,
  multiCourseDiscount: 692,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 692,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
},
{
  code: 'EP',
  name: 'Event and Wedding Planning',
  primary: false,
  cost: 1384,
  multiCourseDiscountRate: 0.5,
  multiCourseDiscount: 692,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 692,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
},
{
  code: 'EB',
  name: 'Accelerate Your Business Workshop',
  primary: false,
  cost: 1039,
  multiCourseDiscountRate: 0.5,
  multiCourseDiscount: 519.5,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 519.5,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
},
{
  code: 'ED',
  name: 'Event Decor',
  primary: false,
  cost: 1039,
  multiCourseDiscountRate: 0.5,
  multiCourseDiscount: 519.5,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 519.5,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
},
{
  code: 'PE',
  name: 'Promotional Event Planning',
  primary: false,
  cost: 695,
  multiCourseDiscountRate: 0.5,
  multiCourseDiscount: 347.5,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 347.5,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
},
{
  code: 'LW',
  name: 'Luxury Wedding & Event Planning',
  primary: false,
  cost: 695,
  multiCourseDiscountRate: 0.5,
  multiCourseDiscount: 347.5,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 347.5,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
},
{
  code: 'FL',
  name: 'Festivals & Live Events',
  primary: false,
  cost: 695,
  multiCourseDiscountRate: 0.5,
  multiCourseDiscount: 347.5,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 347.5,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
},
{
  code: 'DW',
  name: 'Destination Wedding',
  primary: false,
  cost: 695,
  multiCourseDiscountRate: 0.5,
  multiCourseDiscount: 347.5,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 347.5,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
},
{
  code: 'VE',
  name: 'Virtual Events',
  primary: false,
  cost: 400,
  multiCourseDiscountRate: 0.5,
  multiCourseDiscount: 200,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 200,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
},
{
  code: 'TT',
  name: 'Travel and Tourism',
  primary: false,
  cost: 898,
  multiCourseDiscountRate: 0,
  multiCourseDiscount: 0,
  promoDiscount: 0,
  shippingDiscount: 0,
  discountedCost: 0,
  plans: { full: {}, part: {} },
  shipping: 0,
  free: false,
  discountMessage: null
}];


const sorted1 = courses.sort((a, b) => (a.free === b.free ? a.cost - b.cost : a.free ? 1 : -1));

console.log(sorted1);

const sorted2 = courses.sort((a, b) => 0);

console.log(sorted2);